version: '3.8'

services:
  producto-api:
    build:
      context: .
      dockerfile: src/Producto/Producto.API/Dockerfile
    ports:
      - "5100:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-net

  inventario-api:
    build:
      context: .
      dockerfile: src/Inventario/Inventario.API/Dockerfile
    ports:
      - "5101:8080"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
